<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - The NJ TRANSIT portion of this joint ticket will expire 30 days</name>
   <tag></tag>
   <elementGuidId>0f8f1fc5-4f1c-452e-99a7-63f2b0fc6a8b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>f3eb74ef-575d-480a-9e09-5c2ec2e1e6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c53bdc7f-85db-421a-8aee-3c43c387d80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8f2b1e6e-bb39-475a-86a7-4f2dc0bc7fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>522.0</value>
      <webElementGuid>010789e7-e7f0-4ce0-895c-892d45453e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0e90be3c-3519-4259-9224-f0d9b4c6f4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value> The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.</value>
      <webElementGuid>319a40b7-7c16-4721-bc23-20423c71d576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value> The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.</value>
      <webElementGuid>6dfeca93-5b87-45f2-bf0e-493e6d95908b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value> The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.</value>
      <webElementGuid>3558900c-7a61-442a-a3a0-7418a8f0af24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1a94ce47-0f6f-4bea-b5cf-e6ae15cb2ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>478.0</value>
      <webElementGuid>75ef3155-b909-40f7-819f-a497c6a21c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>154.0</value>
      <webElementGuid>b5b104d3-0f8b-45a2-8d3d-7de546508d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>592.0</value>
      <webElementGuid>1ab39965-92f8-49c5-9f58-0e9634f1d3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      <webElementGuid>23e79d0d-1471-40c8-9905-908de84568a4</webElementGuid>
   </webElementProperties>
   <locator>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</locator>
   <locatorCollection>
      <entry>
         <key>ACCESSIBILITY</key>
         <value> The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == ' The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.' AND name == ' The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.' AND name == ' The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.'</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value> The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = ' The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.' and @name = ' The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.' and @value = ' The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ID</key>
         <value> The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector().enabled(true).index(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == ' The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.' AND name == ' The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.' AND value == ' The NJ TRANSIT portion of this joint ticket will expire 30 days from the date of purchase.  The SEPTA portion of this joint ticket will expire 180 days from the date of purchase.  Tickets are valid in either direction.'`]</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>XPATH</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
