<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Enter the email address associated with your NJ TRANSIT</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>de0f85f8-270c-4ee4-8a31-632752f5d667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0252a50f-d608-44b1-a4c9-1dd8a4c54b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0d797c46-ba98-4832-b143-0a6fef569718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>96.0</value>
      <webElementGuid>62452e77-40c8-45c7-8cd8-4de63beba4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3d2e893e-8ff0-4eaf-a078-e2bb67c88657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.</value>
      <webElementGuid>b1b2c0ef-b75b-473b-9b43-1439c719b320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.</value>
      <webElementGuid>41293114-3835-4c8a-9605-4156fa44fd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.</value>
      <webElementGuid>e605d91f-99df-43d1-88d7-a2212c956eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>53ddaf2c-8380-4f98-892a-9cf99de49166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>606.0</value>
      <webElementGuid>83f624cd-f9dc-45af-9279-347ed4f7faec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>80.0</value>
      <webElementGuid>d0c8e06a-0281-428e-9890-3dbd6370c2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>446.0</value>
      <webElementGuid>5bbb66fd-79c5-49f2-870b-c6bcfbc5dcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      <webElementGuid>fcfaf295-fa01-409b-91b8-831873208ec4</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.' and @name = 'Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.' and @value = 'Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.']</locator>
   <locatorCollection>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.' AND name == 'Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.' AND value == 'Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.'`]</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.' AND name == 'Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.' AND name == 'Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.'</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.' and @name = 'Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.' and @value = 'Enter the email address associated with your NJ TRANSIT APP account and we will email instructions to reset your password.']</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
