<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Weve sent a security code to your email address</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>55600e52-a87a-43b5-a500-b9ef2a888947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b078cab-3789-4fe5-b742-728e5dd7ce6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bb74b8e4-5a1c-43e1-b05d-11d33beb5177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>96.0</value>
      <webElementGuid>03352830-5328-49af-9bf9-46766d31b642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e62259a6-c2a1-4b93-9907-b6a63bbb7bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.</value>
      <webElementGuid>cc9ca168-0310-4333-95b8-bd00091e3f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.</value>
      <webElementGuid>a0ef7e36-e250-4478-ae26-770871e5e9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.</value>
      <webElementGuid>e279cdd3-6d7f-4012-a16a-c39edd01bea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a5ad625e-d343-4115-bee9-c24787ba0bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>620.0</value>
      <webElementGuid>693addeb-2158-4ff4-b764-12a8b4da9016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>80.0</value>
      <webElementGuid>56af3397-e286-4ce4-8d26-de0249a1e11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>874.0</value>
      <webElementGuid>b714b011-8d96-4f71-8e15-e1c53fd71c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      <webElementGuid>ade81ac5-1ce2-4fc2-b2c7-eadff8f03a9b</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.&quot;) and @name = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.&quot;) and @value = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.&quot;)]</locator>
   <locatorCollection>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.' AND name == 'We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.' AND value == 'We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.'`]</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.' AND name == 'We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.' AND name == 'We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.'</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.</value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.&quot;) and @name = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.&quot;) and @value = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.&quot;)]</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
      </entry>
      <entry>
         <key>CUSTOM</key>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
