<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText -   A verification code will be sent to rtmaildrop.cc  Is this email correct</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>464d7644-51ab-4a0e-b3eb-046cad9ea69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7fe310de-4037-4da2-be1e-d28bb3a65c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>349d5a6d-a504-472f-a766-e780c7862acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>206.0</value>
      <webElementGuid>2fc49ddd-7f9a-4803-94a9-b0af86056cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6ccb74b2-3268-4953-8707-04fe32a819e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>  A verification code will be sent to rt@maildrop.cc  Is this email correct?</value>
      <webElementGuid>646e7e67-17e1-4c76-8689-6db283a1df61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>  A verification code will be sent to rt@maildrop.cc  Is this email correct?</value>
      <webElementGuid>0ced77b1-7564-44e6-8a56-ce0b1d79ab8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>  A verification code will be sent to rt@maildrop.cc  Is this email correct?</value>
      <webElementGuid>c930140c-1bc1-4a84-b91e-17d9f7a3a039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2f342f8d-3d12-4195-b8b4-447f927bf46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>476.0</value>
      <webElementGuid>08a9f82a-e27d-44f3-8e64-6ffd1f85aefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>152.0</value>
      <webElementGuid>ae79d5de-8692-4ac6-a9e8-e73d375c5352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>730.0</value>
      <webElementGuid>d69823bf-bf4f-49e7-baa0-294e530d101b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[3]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      <webElementGuid>fd0ee43c-3603-4fb3-b3ac-84f074e2a439</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = '  A verification code will be sent to rt@maildrop.cc  Is this email correct?' and @name = '  A verification code will be sent to rt@maildrop.cc  Is this email correct?' and @value = '  A verification code will be sent to rt@maildrop.cc  Is this email correct?']</locator>
   <locatorCollection>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>  A verification code will be sent to rt@maildrop.cc  Is this email correct?</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == '  A verification code will be sent to rt@maildrop.cc  Is this email correct?' AND name == '  A verification code will be sent to rt@maildrop.cc  Is this email correct?' AND name == '  A verification code will be sent to rt@maildrop.cc  Is this email correct?'</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == '  A verification code will be sent to rt@maildrop.cc  Is this email correct?' AND name == '  A verification code will be sent to rt@maildrop.cc  Is this email correct?' AND value == '  A verification code will be sent to rt@maildrop.cc  Is this email correct?'`]</value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = '  A verification code will be sent to rt@maildrop.cc  Is this email correct?' and @name = '  A verification code will be sent to rt@maildrop.cc  Is this email correct?' and @value = '  A verification code will be sent to rt@maildrop.cc  Is this email correct?']</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>  A verification code will be sent to rt@maildrop.cc  Is this email correct?</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[3]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>ID</key>
         <value>  A verification code will be sent to rt@maildrop.cc  Is this email correct?</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
