<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Passwords must contain</name>
   <tag></tag>
   <elementGuidId>70830ff0-5ffe-46fc-ad24-8ab81da6da1b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>99821d21-5c30-4fbb-9fb3-a4fa4aa430d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>40a610cc-dc55-4705-8477-2e1b10c3f91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>243ad87b-ac7e-4adc-9e51-b5979d85de27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>190.0</value>
      <webElementGuid>7b699a1a-da7a-47a5-a920-3d683b3c3d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>8f66fb5a-e321-492b-a77c-3514345d8ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.</value>
      <webElementGuid>bb3e975c-58f5-4f24-bc09-666a855e8c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.</value>
      <webElementGuid>2d9da001-ce8e-41db-97fc-3c5a2fb1eea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.</value>
      <webElementGuid>2d17d5e2-85d4-4038-8a7d-a99b15f4a134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ed697d58-1129-443e-83b0-d32c012f6ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>392.0</value>
      <webElementGuid>f0c693f4-e511-4ebf-998e-b5464865bfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>80.0</value>
      <webElementGuid>a02d4bec-67f7-48ca-af73-670aad4184dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>516.0</value>
      <webElementGuid>0951ecbb-2154-4f3e-b730-ba79a414cc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[4]</value>
      <webElementGuid>94972f01-766d-4d04-9f35-7df16fbe2691</webElementGuid>
   </webElementProperties>
   <locator>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[3]</locator>
   <locatorCollection>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeStaticText[@name=&quot;Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.&quot;]</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.' AND name == 'Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.' AND name == 'Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.'</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[3]</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.' AND name == 'Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.' AND value == 'Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.'`]</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector().enabled(true).index(6)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>Passwords must contain: 8 to 20 characters One UPPERCASE letter One number or numerical value Atleast one Special character ;‘`[and] are not allowed.</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
