<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Weve sent a security code to your email address</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>79fdd362-b5b1-4655-9008-21b6b72884ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>35019326-a2a3-4d75-bd27-a897fbc2b67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f069c54-a26b-4003-86db-fbf92fa08c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>96.0</value>
      <webElementGuid>f8755dd6-210f-4d85-bcf5-a8110ed6b2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9a887015-e2b4-4b8b-8461-476269eaa1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.</value>
      <webElementGuid>e02ffa47-1a57-41df-b85b-2a8cffc09667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.</value>
      <webElementGuid>1964d977-0d38-41c5-84dc-8b523e78ae7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.</value>
      <webElementGuid>f7b7448d-4f59-4c99-9195-ba79fab37ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0cdf2a46-2878-4d22-ade1-2070d499c438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>620.0</value>
      <webElementGuid>9d49abc7-7810-4cfe-9bcc-d93b0473e7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>80.0</value>
      <webElementGuid>df39df21-5f77-4b1c-8860-70936aa01c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>446.0</value>
      <webElementGuid>05d1464e-44df-4379-99c3-dd2c97e58b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      <webElementGuid>c9fd238a-40a9-4816-885e-8004b59218aa</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.&quot;) and @name = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.&quot;) and @value = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.&quot;)]</locator>
   <locatorCollection>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.' AND name == 'We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.' AND value == 'We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.'`]</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.' AND name == 'We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.' AND name == 'We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.'</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>ID</key>
         <value>We've sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.</value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.&quot;) and @name = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.&quot;) and @value = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent a security code to your email address. Please check your inbox and enter the code below to complete your account setup.&quot;)]</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
      </entry>
      <entry>
         <key>CUSTOM</key>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
