<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Please fill-out all of the required fields</name>
   <tag></tag>
   <elementGuidId>117b8823-7d5c-433c-bc8a-d8da742316f8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>a4c9f342-f7b5-48a5-bf94-bd2452955fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b5dadefc-be74-4a2e-b72e-1faf516ff7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85840b62-860a-4b32-8b96-3fb52e81f32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>402.0</value>
      <webElementGuid>17237a31-2793-42d9-aeec-37c5613cf819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>67021c89-d682-49a4-ba1b-7f2db9da0d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value> Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-</value>
      <webElementGuid>9a0d2c9c-9b67-4584-a712-dff823d73a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value> Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-</value>
      <webElementGuid>16fab7cd-09c2-4079-95ee-89811d4736ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value> Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-</value>
      <webElementGuid>8299745b-1670-45e5-b003-2a10b12a5271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0623d96b-955a-4ca5-8847-1ab658de1554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>476.0</value>
      <webElementGuid>801dbbef-9391-412b-8e53-206a72a7809a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>152.0</value>
      <webElementGuid>74cfb295-a760-4781-b2ce-4b1050a0504e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>634.0</value>
      <webElementGuid>575feaca-aaf7-4eb9-a1c5-7a9a8f63c867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[3]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      <webElementGuid>2ef0f160-357f-4f8b-a52b-3bd2498b2f5c</webElementGuid>
   </webElementProperties>
   <locator>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[3]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</locator>
   <locatorCollection>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[3]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value> Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == ' Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-' AND name == ' Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-' AND value == ' Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-'`]</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value> Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == ' Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-' AND name == ' Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-' AND name == ' Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-'</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>ID</key>
         <value> Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-</value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = ' Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-' and @name = ' Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-' and @value = ' Please fill-out all of the required fields.  Passwords must contain:  • 8 to 20 characters • One UPPERCASE letter • One number or numerical value • One of following special characters. ~!@#$%^&amp;*()_+=|:&quot;&lt;,>.?/{}-']</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector().enabled(true).index(1)</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
      </entry>
   </locatorCollection>
   <locatorStrategy>XPATH</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
