<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Congratulations Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>f66d6918-b75b-4218-a84e-16f89243f177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3b7ea047-66cf-4232-8cd3-13576cfde281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>66c8a9fb-0d50-4fc6-98be-29e6e1567038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>128.0</value>
      <webElementGuid>3ea8051b-5dd6-406a-93b5-fece9f2165ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1f90bec6-9295-4cdb-8f77-47aa7c6103c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.</value>
      <webElementGuid>305446d3-9251-40f0-b273-c2f6dd7eaf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.</value>
      <webElementGuid>55e7b098-7b38-4db7-ac6d-36b94ecfe371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.</value>
      <webElementGuid>a7d65a34-145a-4f5c-814e-98686bf56be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8feb1d5b-8152-4e08-a095-eb1cb387421a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>616.0</value>
      <webElementGuid>9158970c-ed0e-40f8-aece-889f66335567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>80.0</value>
      <webElementGuid>8a7a4241-01ac-4a92-b0df-18a15798b180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>446.0</value>
      <webElementGuid>00b3d129-7afa-4023-8d4a-cb7f2df53964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      <webElementGuid>8722a143-2d14-4889-9d97-e15ceb2022eb</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.' and @name = 'Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.' and @value = 'Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.']</locator>
   <locatorCollection>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.' AND name == 'Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.' AND name == 'Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.'</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.' AND name == 'Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.' AND value == 'Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.'`]</value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.' and @name = 'Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.' and @value = 'Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.']</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Congratulations! Your account has been created. You can now explore custom options and favorites. If you have any questions, our support team is here to help.</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
